# © 2021 FeRD (Frank Dana)
#
# SPDX-License-Identifier: CC0-1.0

# Workflow to run 'reuse lint' via the reuse-action script,
# which will flag any files added or changed in the repo
# that don't have valid, verifiable license data associated
# with them. See the .reuse/ directory in the repo, and
# for more information visit https://reuse.software/

name: Validate source licensing

on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.1.1
